### ISSUE TITLE
对于“超时”的题目，如何优化

### ISSUE THREAD

**Issue by JavaProgrammerLB** [konieshadow/leetcode#1]
对于“超时”的题目，优化的思路有哪些？  
如何量化评估自己代码的访问时间？

**Comment by konieshadow** [comment]
“超时”的那个题目我想了很久，最后解决了，[见这里](https://github.com/konieshadow/leetcode/blob/master/isSelfCrossing/index.js)。
评估代码执行时间，可以在开始执行时记一下系统时间，在执行结束后与当前系统时间比较。也可以使用linux上的time命令，比如：

`time python main.py`
